version: '3'

services:
  db:
    container_name: pic-diary-db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "picture-diary"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_pass"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
